name: google_ads_env
channels:
  - knime
  - conda-forge
dependencies:
  - python=3.11
  - knime-python-base
  - knime-extension
  - google-ads=27.0.0
  - google-api-python-client
  - conda-forge::protobuf=4.25.3 # Newer versions are lacking _message.cp311-win_amd64.pyd causing an import error.
